name: Development Environment
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    name: Deploy Development Environment
    runs-on: ubuntu-latest
    steps:
      - name: Connect to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            whoami
            ls -al